### ISSUE TITLE
Suggestion: use JS Prettier for formatting

### ISSUE THREAD

**Issue by kwshi** [hyperschedule/hyperschedule#109]
This is a style/workflow suggestion.  Currently, all code formatting (indentation, braces placement) is done _by hand_.  This makes it easy, especially since we have more contributors now, to have inconsistent style across the codebase (two-space indent in some places vs. four-space in others; braces on same line as `if`s vs. on new lines here and there; etc.).  

Sometimes, habits are habits, and even when I'm reminding myself to stick to the existing style, I often miss a few and accidentally put my braces on the same line, purely out of habit.  Instead of making it a burden on maintainers/reviewers to manually check style, why not use an automatic formatting tool?  

[Prettier](https://prettier.io/) is a nice, simple JS tool that _deterministically_ (i.e. syntactically equivalent code is _guaranteed_ to return the same formatting) formats JS code that is opinionated about formatting so we, as developers, don't have to be.

Here's how I propose we do this:
- First, format all of `hyperschedule.js` using Prettier in a new PR, and merge it.
- Subsequent changes to `hyperschedule.js` must be formatted using Prettier before they are merged; there are a few ways to enforce this:
  - _Tell_ developers to do so, and remind them to do it again if they forget before merging PRs (more manual work).
  - Set up some git commit hooks to either prevent git commits if the codebase is not formatted, or to auto-format JS files before each commit (more automatic, better consistency on all _commits_, not just PRs, but slightly trickier to setup)

**Comment by raxod502** [comment]
Yes, we should clearly be using Prettier. Let's just have the CI run Prettier and fail the build if there's a difference. Then we can also automatically install a pre-commit hook using [lint-staged](https://github.com/okonet/lint-staged). I've set this up before; check out https://github.com/raxod502/cs121-whales/blob/develop/.lintstagedrc for an example.

It should be possible to disable the pre-commit hook (or its installation) using an environment variable or some other mechanism, so that people who (like me) have their editor configured to run Prettier on every file save don't have to wait longer to finish a commit.

**Comment by raxod502** [comment]
I suggest we use CircleCI for the CI. Here's an example configuration: https://github.com/raxod502/radian/blob/develop/.circleci/config.yml.

Of course, if we start using CI, we should also start using Docker, because otherwise setting up CI is a real pain, and so is migrating between services.

Since I have a strong comparative advantage at setting up all of these things based on my past experience (and since I've wanted this for a while), I'll take this issue.

**Comment by raxod502** [comment]
Implemented in https://github.com/MuddCreates/hyperschedule/commit/7eb92a3ea07eb79d09339d0ac4fa05345793fa7f, https://github.com/MuddCreates/hyperschedule/commit/81e716ed71ed6e9b7c870fbe1d4a83f75420c73b, and https://github.com/MuddCreates/hyperschedule/commit/c477c31609156f8107b3965885d136f856f0b32e.
