### ISSUE TITLE
Include info on class prerequisites/PERM only

### ISSUE THREAD

**Issue by kipmacsaigoren** [hyperschedule/hyperschedule#123]
I'm not sure if there's a way to get this info from portal, but there should be a way to know if the class has prerequisites or requires instructor permission. I know some classes include this in the description, but when they don't it becomes confusing as to what is and isn't required. Thanks!

**Comment by raxod502** [comment]
Unfortunately, the chances of this happening are pretty slim. We currently merge data from the course search results page on Portal together with data from the hacky API database dump that the registrar emails me every semester, so if the data isn't available from one of those sources, there's probably not much hope (since scraping each individual course on Portal is much slower and harder). We'll have to wait until the new Portal is installed next year and see how that changes the landscape.

**Comment by kipmacsaigoren** [comment]
That's super interesting to know, thanks for the response! Is there any information on the new portal being sent out next year?

**Comment by raxod502** [comment]
Not to my knowledge, sorry.
