### ISSUE TITLE
Credit Search Keyword

### ISSUE THREAD

**Issue by JeremyTsaii** [hyperschedule/hyperschedule#131]
User Story:

As a user, I want to filter classes by course credits so I can create a schedule with the number of units I want. There have been scenarios where I want to search for 1 credit classes since I am at the cusp of overloading (16 or 17 credits), but there has been no way of looking for such courses, even on Portal. Having such a feature would allow for me to easily find classes with a specified amount of credits and help in crafting my schedule.

Implementation:

- [x] Add credit keyword

The user will be able to enter a query like “1 credit” and classes that are 1 credit will show up in the search results. We also want the user to be able to input other keywords before/after the time/day keywords to further narrow their searches.

![credit keyword](https://github.com/JeremyTsaii/Images/blob/master/credit.JPG)

This is part of CS121 Group 2. Team members include @JeremyTsaii, @godpng, @rory6103.

**Comment by kwshi** [comment]
This sounds like a great idea that Hyperschedule can readily use.  

In the interest of consistency and simplicity, I'm inclined to suggest that we do so using Hyperschedule's existing GitHub-style "keyword" filtering mechanism (you can read more about it by clicking the "How does it work?" button in the Hyperschedule UI), instead of fuzzy-matching for search strings containing "n credits".  This means we would filter on credits not by querying things like "1 credit" or "2 credits" but rather adding keywords like "credits:1" and "credits:3", etc.  

Also worth considering are more sophisticated filtering like "credits:<3" or "credits:<=3" to filter credits with inequalities.

If that sounds good to you, the relevant code to look at right now is the `filterKeywords` global and the `coursePassesTextFilters` function.

I can see a case made, however, for fuzzy syntax like "1 credit" because it's slightly more intuitive (maybe) to use and doesn't require knowing special syntax.  But I personally find that it would make parsing quite complicated and, past a certain point, unpredictable, kind of like Google search queries.

**Comment by JeremyTsaii** [comment]
Thanks Kye.

Regarding using the keyword filtering mechanism, that is actually what we have done! Our pull request detailing the implementation will come in the next few days. We have also changed the help modal accordingly to show the new filter keywords.

The inequality filtering idea for credits is quite interesting and we will try to get that working.

Thanks for the suggestions and feedback.
