### ISSUE TITLE
FirebaseUI Authentication

### ISSUE THREAD

**Issue by ssantichaivekin** [hyperschedule/hyperschedule#132]
We will connect the frontend to FirebaseUI authentication. After the user logs in via gmail, firebase will give us the user information and a [token](https://firebase.google.com/docs/auth/admin/verify-id-tokens). We can use that token in our backend to verify the identity of user. A separate issue for the backend is submitted [here](https://github.com/MuddCreates/hyperschedule-api/issues/11).

Authentication will
- allow user to save courses and display it in different devices.
- allow safe upload of crowdsource information such as syllabus.

Tasks:

- [x] Setup authentication database in Firebase.
- [x] Add Firebase UI authentication to the frontend.
- [ ] Make a nice Sign In and Sign Out button.
- [ ] Test that after we sign in, we can send a post request to the `/api/auth_hello` with our token.

**Comment by kwshi** [comment]
It seems like this issue is tracking progress on a WIP fork of Hyperschedule.  I've recently thought a bit about authenticating, and I think I'm going to end up using Netlify's own authentication tools ("Netlify Identity") for this.  Closing for now because of inactivity; feel free to reopen if you want to continue working on this and reclaim the login project.
