### ISSUE TITLE
Syllabus Upload Functionality

### ISSUE THREAD

**Issue by nefrathenrici** [hyperschedule/hyperschedule#144]
**User Story:** As a user, I want to be able to look at syllabi from previous semesters. This will be give me more information about the classes I want to take, and will allow me to plan better.

**Implementation**: We will allow users signed in with a 5C email to upload and view syllabi from previous semesters. Users will sign in through Google authentication using Firebase. The syllabus link will be at the bottom of the course description box and different sections of a course will have their own syllabus. If a course does not have a syllabus uploaded already, there won't be a link, just a button which will open the upload modal when clicked. 

The upload modal lets the user select the semester and a PDF to upload. It also displays information about the syllabus's upload status, so that they know if the upload has worked or not. 

The file and the semester will be passed to the backend through Fetch, which will store the file in Firebase storage. The backend's full implementation will be detailed in an issue in the hyperschedule-api repo, but the semester and a link to the uploaded syllabus file will be added to the courses.json file to be used in the frontend.

When a syllabus has been uploaded, the user will be able to click a link at the bottom of the course description box, and it will open in another tab. They will also be able to upload a newer version of the syllabus.

**Comment by jbecker7** [comment]
Has any progress been made on this? This sounds like a really cool feature (though I do wonder what the colleges would think... would be awesome to be able to see what textbooks are used for a class and what the syllabus is.

**Comment by mia1024** [comment]
We won't implement this feature because some professors do not like their syllabi being publicly available, as some of them have fairly personal things in their syllabi. Also, there is no way to make sure whatever user uploaded is up-to-date. Even if we display which semesters the uploaded syllabi are for, it's fairly likely that users will be mislead by an outdated syllabus after a course overhaul that the users are unaware of. In general, if you want a syllabus for a course, you should email the professor.
