### ISSUE TITLE
Feature Request: Number of PERMs and Pre-Reqs

### ISSUE THREAD

**Issue by JarredAllen** [hyperschedule/hyperschedule#164]
I don't know much about the internals of portal or hyperschedule, so idk if this is doable, but I think it'd be nice if we could see the prereqs for a course and the number of perms from within hyperschedule.

**Comment by kwshi** [comment]
I absolutely agree!  Currently, there's not exactly a practical way to do that with Portal, for the reason that in order to get that information our scraper would have to click into each one of the courses individually, which would take about ~2000 courses * ~5 sec/course = ~10000 sec = ~3 hours.  _But_ we're looking into ways to get data other than from Portal (which we do literally by simulating a browser, so whatever you can see from a list of search results when you search for courses is what we retrieve), such as:
- Getting a back-alley CSV, fresh from the Portal databases, from the HMC IT department--this is how we currently get course descriptions and is also the reason sometimes course descriptions don't match up with their course codes/are not up to date, because the CSV needs to be manually updated (and I haven't done so this round), see #163.
- HMC has announced they're planning to migrate away from Portal to a new Workday Student system by Fall 2022 or so.  Allegedly, Workday provides official APIs and would, in theory, facilitate getting this data much, much more easily and reliably than Portal allows; we're hoping, for now, that when that new platform+API drops, that it'll solve all our problems with data retrieval, and we'll be sure to take this suggestion into account then, when we write code for the new API.
