### ISSUE TITLE
Not showing courses with multiple letters after the course number

### ISSUE THREAD

**Issue by skylar73** [hyperschedule/hyperschedule#172]
For example, MATH 189AC is not listed on hyperschedule but exists on portal. (While MATH 189B does appear on both hyperschedule and portal)

**Comment by kwshi** [comment]
Thanks for the report!  I've looked into it--this seems like a problem with the ZIP file data we're receiving from HMC admin (long story short: after [a complaint](https://github.com/MuddCreates/hyperschedule/issues/158) that Hyperschedule was overloading Portal, we were forced to change how we retrieve course data--instead of scraping it straight from Portal, we now receive data in the form of a ZIP file containing sometimes-inaccurate course data via an automated email every 5 minutes).  I'll contact them about this to see if we can get it fixed.

**Comment by kwshi** [comment]
I believe this is now fixed.  Feel free to open another issue if you find another course on Portal that doesn't appear on Hyperschedule.
