### ISSUE TITLE
Still Broken?

### ISSUE THREAD

**Issue by cossa7901** [hyperschedule/hyperschedule#173]
I'm not sure if other people have still been having this problem, but whenever I open Hyperschedule it continues to appear empty. It'll pull up my previously downloaded classes from last semester (using the import data button), but hasn't pulled up anything fresh for the past few months. I know I already saw an issue about this, but I'm not sure if it's been resolved and I somehow need to update the link, or if it's still bugging, or if I should be doing something entirely different?

**Comment by kwshi** [comment]
Hi @cossa7901, sorry you're facing this issue!  I spent all of yesterday trying to fix a bunch of bugs w/ Hyperschedule & get it ready for the upcoming registration season; is it still broken?  I believe it _should_ be working correctly right now.

**Comment by widdakay** [comment]
I was able to replicate the issue and it does make hyperschedule nonfunctional for new users. It appears to be an access control header issue. My guess is that everyone who sees courses sees old courses from the last time it worked which are stored in their local storage. If you clear that, it never re-downloads the courses and you can see it retrying every second or so to download the courses. Edit: This has been verified by getting a copy of the local cache from another person who has the courses and then hyperschedule works as expected (though it still does not update courses due to the incorrect Access-Control-Allow-Origin header). 

It gets the error: ```Access to fetch at 'https://hyperschedule.herokuapp.com/api/v3/courses?school=hmc' from origin 'https://hyperschedule.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.``` meaning that hyperschedule.io needs to be added to the Access-Control-Allow-Origin header.

**Comment by kwshi** [comment]
Actually, you're getting that error right now because the backend crashed (for some reason--my bad code, probably).  It should be working now; try opening hyperschedule.io in incognito (which prevents any cache from getting used) and see if it works.

(Meanwhile, a fix _is_ quickly on its way to make sure these crashes don't happen anymore!)
