### ISSUE TITLE
Code is bad

### ISSUE THREAD

**Issue by kwshi** [hyperschedule/hyperschedule#22]
Code is becoming very bad.  Everyone is hacking things together.  Sense of organization and coherence and unity and structure and simplicity and elegance is crumbling help what can we do we need a major refactor this is a disaster

**Comment by kwshi** [comment]
Also it's late and I need sleep

**Comment by raxod502** [comment]
I recommend that everyone follow the existing conventions of the project instead of introducing new ones. Separating frontend code into separate files would almost certainly help. And, doing a "major refactor" almost never helps unless it's an entirely different team doing the refactor—if we can't make it work with the existing code, it's unlikely that we'll be able to make it work with new code.

**Comment by kwshi** [comment]
Would it be a useful thing to bunch things up into classes instead of, say, littering the global namespace with `courseToString` and `coursesEquivalent` and related functions? This would in principle make some things look nicer and make separating things into separate files easier, too.

**Comment by raxod502** [comment]
Not sure. Certainly it could be useful. At the end of the day, the rule is whatever makes the code easier to understand and safely modify. If you think these aspects are improved by taking an object-oriented approach, I have no objection.

**Comment by raxod502** [comment]
Closed in favor of #33.
