### ISSUE TITLE
Allow saving particular schedules

### ISSUE THREAD

**Issue by blakeLarkin** [hyperschedule/hyperschedule#3]
This is just an idea for future additions, but the best thing in my opinion about the old (pre-CSearch) scheduler was the ability to star/save entire schedule layouts and to switch between them. Its good to figure out individual classes with your starring and ordering system, but it can take a long time if you are switching between two very different schedules based on a difficult-to-get class. Could you offer a way to save the state of the class order, stars, and disables to quickly switch between them?

**Comment by raxod502** [comment]
Sure, this is not something I'm opposed to. At the moment, Hyperschedule is not really designed for the "schedule micromanagement" use case, but more rather for people who are fine with registering for any combination of their favorite classes. I don't see why in future it can't support both use cases.

Would only saving starred courses, rather than also selected courses, be sufficient?

**Comment by raxod502** [comment]
Note that you can achieve this functionality by copying the JSON from the import/export modal to and from external files.

**Comment by mia1024** [comment]
Implemented in the new version
