### ISSUE TITLE
PDF export should include class location, professor

### ISSUE THREAD

**Issue by raxod502** [hyperschedule/hyperschedule#67]
Currently, the PDF export only shows course code and name. It should have the same metadata as the iCal export. cc @kwshi

**Comment by Owen-Gillespie** [comment]
I'm going to shoot to work on this issue this week. I would like to throw out that we should ditch the full course name and instead include some subset of professor, location, and time

**Comment by raxod502** [comment]
Great!

It seems to me like all the information can fit, but I haven't seen what that would look like. If you judge that the aesthetics suffer significantly, then I'd be fine with leaving out the full course name as long as we still have the course code.

**Comment by Owen-Gillespie** [comment]
Threw together a quick version of what it would look like with all of this info.
![image](https://user-images.githubusercontent.com/8729135/48145701-419bb600-e268-11e8-90bb-b53595d3d7b3.png)

Given that there is both a 1-hour slot with a short name that overflows and a 1.5 hour block with a long name that overflows, we clearly have to make an adjustment. One option is to have a priority order for the information and only add to a given block if we have space. Another option that would help is to have a mapping for colloquial names (i.e. Shan instead of Shanahan
Center). This could be done pretty easily at least for Mudd. Also we could use smaller text, but I think this is probably a bad UX decision

**Comment by Owen-Gillespie** [comment]
Threw together what it would look like if we used the space to display this info with the following priorities
1. (Always) Course code
2. Course location
3. Full name of course
4. Last names of instructors
but in the sequential order
1. Course code
2. Full name of course
3. Last names of professors
4. Course location

![image](https://user-images.githubusercontent.com/8729135/48162877-18444f80-e293-11e8-96a0-420ba8675736.png)

Still need to iron out some issues with spacing, but does this seem like a good solution?

**Comment by raxod502** [comment]
Seems good to me. Thanks for working on this!
