### ISSUE TITLE
Gets slower over time

### ISSUE THREAD

**Issue by raxod502** [hyperschedule/hyperschedule#89]
When I leave a browser tab open for a long time with Hyperschedule, the interface is very laggy (specifically adding and removing courses) when I return to it. There is probably a memory leak related to the API data retrieval.

**Comment by kwshi** [comment]
Regarding memory leaks: one possible source is that the console logs ("Attempting to fetch course data... Successfully...") are creating the memory leak.  I know it sounds a little contrived, since the log is tiny, but I had console.log calls creating a memory leak while working on the React port.  But there I was logging entire API fetches, and the log data here is tiny pieces of plain text, so that explanation is a little less likely.  But i'll throw this possibility out there, FWIW.
